Added interpolation support checker in testing and made CI lints fail after testing instead of before

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -50,10 +50,13 @@ jobs:
 
     - name: Formatting
       if: runner.os == 'Linux'
+      id: fmt
       run: cargo fmt --check
 
     - name: Linting
       if: runner.os == 'Linux'
+      id: lint
+      continue-on-error: true
       run: cargo clippy --bin ridal -- -D warnings --no-deps
 
     - name: Build
@@ -72,6 +75,17 @@ jobs:
     - name: Dry-run cargo publish
       if: runner.os == 'Linux' && !startsWith(github.ref, 'refs/tags/')
       run: cargo publish --dry-run
+
+    - name: Fail job if fmt failed
+      if: runner.os == 'Linux' && steps.fmt.outcome == 'failure'
+      run: |
+        echo "Lint (cargo clippy) failed; marking job as failed."
+        exit 1
+    - name: Fail job if lint failed
+      if: runner.os == 'Linux' && steps.lint.outcome == 'failure'
+      run: |
+        echo "Lint (cargo clippy) failed; marking job as failed."
+        exit 1
 
   publish:
     name: Publish to crates.io
